import type { AuraTheme } from "../themes/index.js";
import type {
  AppMetadata,
  Attachment,
  ChatMessage,
  Conversation,
  MessageRoleType,
  ToolCallLogEntry,
  ToolCallRequest,
} from "./core-types.js";
import type { SettingsModalConfig } from "./settings.js";

/**
 * Information about an AI model.
 */
export interface ModelInfo {
  /** Unique identifier for the model (e.g., "gpt-4"). */
  id: string;
  /** Human-readable name of the model. */
  name?: string;
  /** Icon representation for the model. */
  icon?: string;
  /** Brief description of the model's capabilities. */
  description?: string;
}

/**
 * Configuration options for an AI provider.
 */
export interface ProviderOptions extends Record<string, unknown> {
  /** The model ID to use for requests. */
  model?: string;
  /** Sampling temperature (0.0 to 1.0). */
  temperature?: number;
  /** Maximum number of tokens to generate. */
  maxTokens?: number;
  /** Custom endpoint URL for the provider API. */
  endpoint?: string;
  /** API key for authentication. */
  apiKey?: string;
  /** Bearer token or a function that returns one. */
  authToken?: string | (() => Promise<string>);
  /** List of model IDs to include in the UI. */
  includedModels?: string[];
  /** List of model IDs to exclude from the UI. */
  excludedModels?: string[];
  /** Abort signal to cancel the request. */
  signal?: AbortSignal;
}

/**
 * A message within a provider request or response.
 */
export interface ProviderMessage {
  /** The role of the message sender. */
  role: MessageRoleType;
  /** The text content of the message. */
  content: string;
  /** ID of the tool call this message responds to (camelCase). */
  toolCallId?: string;
  /** ID of the tool call this message responds to (snake_case, for compatibility). */
  tool_call_id?: string;
  /** Name of the tool or user (optional). */
  name?: string;
  /** List of tool calls requested by the assistant (camelCase). */
  toolCalls?: ToolCallRequest[];
  /** List of tool calls requested by the assistant (snake_case, for compatibility). */
  tool_calls?: ToolCallRequest[];
  /** Attachments associated with the message. */
  attachments?: Attachment[];
}

/**
 * Metadata and hints for a tool definition.
 */
export interface ToolAnnotations {
  /** Human-readable title for the tool. */
  title?: string;
  /** Hint that the tool only reads data and doesn't modify state. */
  readOnlyHint?: boolean;
  /** Hint that the tool performs a destructive action (e.g., delete). */
  destructiveHint?: boolean;
  /** Hint that the tool is idempotent (safe to retry). */
  idempotentHint?: boolean;
  /** Hint that the tool interacts with the external world beyond the current context. */
  openWorldHint?: boolean;
  /** Additional custom annotations. */
  [key: string]: unknown;
}

/**
 * Definition of a tool that can be called by the AI.
 */
export interface ToolDefinition {
  /** Unique name of the tool. */
  name: string;
  /** Description of what the tool does. */
  description: string;
  /** JSON Schema for the tool's input arguments. */
  inputSchema: Record<string, unknown>;
  /** The type of tool, usually "function". */
  type?: "function";
  /** Function definition following OpenAI/MCP standards. */
  function?: {
    name: string;
    description: string;
    parameters: Record<string, unknown>;
  };
  /** UI and execution hints. */
  annotations?: ToolAnnotations;
}

/**
 * A full request payload for an AI provider.
 */
export interface ProviderRequest {
  /** Specific model ID to use. */
  modelId?: string;
  /** History of messages in the conversation. */
  messages: ProviderMessage[];
  /** List of tools available for the AI to use. */
  tools?: ToolDefinition[];
  /** Provider-specific configuration options. */
  options?: ProviderOptions;
}

/**
 * @internal Statistics about token consumption.
 * Not part of the public API.
 */
interface TokenUsage {
  /** Tokens used in the input prompt. */
  promptTokens: number;
  /** Tokens used in the generated response. */
  completionTokens: number;
  /** Combined total tokens used. */
  totalTokens: number;
}

/**
 * A combined response from an AI provider.
 */
export interface ProviderResponse {
  /** The text content generated by the AI. */
  content: string | null;
  /** Any tool calls requested by the AI. */
  toolCalls: ToolCallRequest[];
  /** Token usage statistics if available. */
  usage?: TokenUsage;
  /** Additional metadata from the provider. */
  meta?: Record<string, unknown>;
}

/**
 * A partial chunk of a streaming AI response.
 */
export interface ProviderResponseChunk {
  /** Text delta in this chunk (OpenAI style). */
  delta?: string;
  /** Text content delta in this chunk (Anthropic style). */
  contentDelta?: string;
  /** Tool calls in this chunk (snake_case). */
  tool_calls?: ToolCallRequest[];
  /** Incremental updates to tool calls. */
  toolCallDeltas?: Partial<ToolCallRequest>[];
  /** Whether the stream has finished. */
  done?: boolean;
}

/**
 * Interface for implementing a custom AI model provider.
 */
export interface AIProvider {
  /** Unique identifier for the provider. */
  readonly id: string;
  /** Human-readable label (e.g., "Azure OpenAI"). */
  readonly label: string;
  /** Icon for the provider. */
  readonly icon?: string;
  /** Type identifier for the provider implementation. */
  readonly type?: string;
  /** Display name. */
  readonly name?: string;
  /** Update the provider configuration. */
  configure(config: ProviderOptions): void;
  /** Get current configuration. */
  getConfig(): ProviderOptions;
  /** List available models for this provider. */
  listModels(options?: ProviderOptions): Promise<ModelInfo[]>;
  /** Send a message and wait for a full response. */
  sendMessages(request: ProviderRequest): Promise<ProviderResponse>;
  /** Optional stream implementation for real-time responses. */
  streamMessages?(
    request: ProviderRequest,
    options?: ProviderOptions,
  ): AsyncIterable<ProviderResponseChunk>;
}

/**
 * Configuration for a built-in AI provider.
 */
export interface BuiltInProviderConfig {
  type: "built-in";
  /** ID of the built-in provider (e.g., "openai", "anthropic"). */
  id: string;
  /** Configuration options for this provider. */
  config?: ProviderOptions;
}

/**
 * Configuration for a custom-implemented AI provider.
 */
export interface CustomProviderConfig {
  type: "custom";
  /** Unique ID for the custom provider. */
  id: string;
  /** Instance of the AIProvider implementation. */
  config: AIProvider;
}

/**
 * Union type for AI provider configurations.
 */
export type ProviderConfig = BuiltInProviderConfig | CustomProviderConfig;

/**
 * Metadata for content parts (text, images, etc.).
 */
export interface ContentAnnotations {
  /** Who should see this content. */
  audience?: Array<"user" | "assistant">;
  /** Rendering priority. */
  priority?: number;
  [key: string]: unknown;
}

/**
 * Plain text content part.
 */
export interface TextContent {
  type: "text";
  text: string;
  annotations?: ContentAnnotations;
}

/**
 * Image content part.
 */
export interface ImageContent {
  type: "image";
  /** Base64 encoded image data or URL. */
  data: string;
  /** MIME type (e.g., "image/png"). */
  mimeType: string;
  annotations?: ContentAnnotations;
}

/**
 * Audio content part.
 */
export interface AudioContent {
  type: "audio";
  /** Base64 encoded audio data or URL. */
  data: string;
  /** MIME type (e.g., "audio/mpeg"). */
  mimeType: string;
  annotations?: ContentAnnotations;
}

/**
 * Details of text-based resource content.
 */
export interface TextResourceContents {
  uri: string;
  mimeType?: string;
  text: string;
}

/**
 * Details of binary/blob resource content.
 */
export interface BlobResourceContents {
  uri: string;
  mimeType?: string;
  /** Base64 encoded blob data. */
  blob: string;
}

/**
 * A resource embedded within a message or tool result.
 */
export interface EmbeddedResource {
  type: "resource";
  resource: TextResourceContents | BlobResourceContents;
  annotations?: ContentAnnotations;
}

/**
 * @internal Structured JSON content part.
 * Used inside ToolResultContent union, not exported publicly.
 */
interface JsonContent {
  type: "json";
  data: unknown;
  /** Optional label for the data. */
  label?: string;
  annotations?: ContentAnnotations;
}

/**
 * A custom web component to render in the chat.
 */
export interface CustomElementContent {
  type: "custom-element";
  /** The tag name of the custom element (e.g., "my-chart"). */
  element: string;
  /** Properties to pass to the custom element. */
  props: Record<string, unknown>;
  annotations?: ContentAnnotations;
}

/**
 * Union type for all possible tool result content parts.
 */
export type ToolResultContent =
  | TextContent
  | ImageContent
  | AudioContent
  | EmbeddedResource
  | JsonContent
  | CustomElementContent;

/**
 * The output of a tool execution.
 */
export interface AuraToolResult {
  /** Rich result content for UI rendering. */
  content: ToolResultContent[];
  /** Optional machine-readable structured output. */
  structuredContent?: Record<string, unknown>;
  /** Log entry for tracking this execution. */
  logEntry?: ToolCallLogEntry;
  /** Whether the execution failed. */
  isError?: boolean;
  /** Internal metadata. */
  _meta?: Record<string, unknown>;
  [key: string]: unknown;
}

/**
 * Risk levels for tool execution.
 */
export const AuraToolRisk = {
  /** No dangerous side effects, no confirmation needed. */
  Safe: "safe",
  /** Potential side effects, might need confirmation. */
  Moderate: "moderate",
  /** Destructive actions, always should need confirmation. */
  Destructive: "destructive",
} as const;

export type AuraToolRiskType = (typeof AuraToolRisk)[keyof typeof AuraToolRisk];

/**
 * Represents a document or data source that the AI can read.
 */
export interface AuraResource {
  /** Unique resource identifier. */
  uri: string;
  /** Human-readable name. */
  name: string;
  /** Description of the resource content. */
  description?: string;
  /** MIME type if known. */
  mimeType?: string;
  /** Read the resource content. */
  read(): Promise<TextResourceContents | BlobResourceContents>;
}

/**
 * Contextual information provided to a tool during execution.
 */
export interface ToolExecutionContext {
  /** Current conversation ID. */
  conversationId: string;
  /** ID of the user triggering the tool. */
  userId?: string;
  /** Metadata about the host application. */
  appMetadata: AppMetadata;
  /** List of resources available in this context. */
  resources?: AuraResource[];
}

/**
 * Definition and execution logic for a local Aura tool.
 */
export interface AuraTool {
  /** Unique tool name. */
  name: string;
  /** Description explaining when and how to use the tool. */
  description: string;
  /** JSON Schema for input arguments. */
  inputSchema: Record<string, unknown>;
  /** The implementation function. */
  execute: (
    args: Record<string, unknown>,
    ctx: ToolExecutionContext,
  ) => Promise<AuraToolResult>;
  /** Display title for UI. */
  title?: string;
  /** Risk level of the tool. */
  risk?: AuraToolRiskType;
  /** Execution timeout in MS. */
  timeout?: number;
  /** Optional logic to generate a preview before execution. */
  preview?: {
    buildContent: (
      args: Record<string, unknown>,
    ) => Promise<ToolResultContent[]>;
  };
}

/**
 * A group of tools and instructions representing a specific capability.
 */
export interface Skill {
  /** Name of the skill. */
  name: string;
  /** Description of what the skill provides. */
  description: string;
  /** Specific instructions for the AI on how to use this skill. */
  instructions?: string;
  /** List of tool names included in this skill. */
  tools: string[];
  /** Custom metadata. */
  metadata?: Record<string, unknown>;
}

/**
 * Types of events emitted by the Aura system.
 */
export enum AuraEventType {
  ConversationStarted = "conversation-started",
  ConversationEnded = "conversation-ended",
  ConversationDeleted = "conversation-deleted",
  ChatClosed = "chat-closed",
  HistoryCleared = "history-cleared",
  MessageSent = "message-sent",
  MessageReceived = "message-received",
  ToolCalled = "tool-called",
  ToolStart = "tool-start",
  ToolSuccess = "tool-success",
  ToolError = "tool-error",
  SkillSelected = "skill-selected",
  AgentLoopStarted = "agent-loop-started",
  AgentLoopCompleted = "agent-loop-completed",
  AgentStepStarted = "agent-step-started",
  AgentStepCompleted = "agent-step-completed",
  Debug = "debug",
  Error = "error",
  McpServerConnecting = "mcp-server-connecting",
  McpServerConnected = "mcp-server-connected",
  McpServerDisconnected = "mcp-server-disconnected",
  McpServerError = "mcp-server-error",
  McpToolsRegistered = "mcp-tools-registered",
  McpToolsUnregistered = "mcp-tools-unregistered",
}

/**
 * A lifecycle event emitted by the Aura system.
 */
export interface AuraEvent {
  /** The event category. */
  type: AuraEventType;
  /** When the event occurred. */
  timestamp: number;
  /** Event-specific data. */
  payload: Record<string, unknown>;
  /** Raw underlying event if applicable. */
  event?: Record<string, unknown>;
}

/**
 * A prompt idea shown to the user in the "Suggested Prompts" section.
 */
export interface SuggestedPrompt {
  /** Quick summary title. */
  title: string;
  /** Detailed description. */
  description?: string;
  /** The actual prompt text to suggest. */
  promptText: string;
  /** Icon to display alongside the prompt. */
  icon?: string;
}

/**
 * Content that supports rich formatting (normally markdown string).
 */
export type RichContent = string;

/**
 * Configuration for an external Model Context Protocol (MCP) server.
 */
export interface McpServerConfig {
  /** Unique ID for the server connection. */
  id: string;
  /** SSE or stdio endpoint URL. */
  url: string;
  /** Whether the server is active. */
  enabled: boolean;
  /** List of tools on this server to keep disabled. */
  disabledTools?: string[];
}

/**
 * Configuration for the AI Agent behavior and tools.
 */
export interface AuraAgentConfig {
  /** Base instructions for the AI model. */
  appSystemPrompt?: string;
  /** Contextual resources available to the agent. */
  resources?: AuraResource[];
  /** Pre-defined skills (tool groups). */
  skills?: Skill[];
  /** Custom local tools. */
  tools?: AuraTool[];
  /** External MCP server connections. */
  mcpServers?: McpServerConfig[];
  /** Implementation for conversation storage. */
  conversationManager?: IConversationManager;
  /** Pre-defined conversation ID to load. */
  conversationId?: string;
  /** Maximum number of tokens for context window. */
  maxContextTokens?: number;
  /** Whether to enable response streaming. */
  enableStreaming?: boolean;
  /** Extra safety constraints for the AI. */
  additionalSafetyInstructions?: string;
  /** Max iterations the agent can take per message. */
  maxIterations?: number;
  /** Whether to show the AI's step-by-step reasoning. */
  showThinkingProcess?: boolean;
  /** Default timeout for tool executions. */
  toolTimeout?: number;
  /** Timeout for pending user confirmations. */
  confirmationTimeoutMs?: number;
  /** Whether to enable WebMCP client for browser-side MCP servers. */
  enableWebMcp?: boolean;
  /** Custom AI model providers. */
  providers?: ProviderConfig[];
}

/**
 * Configuration for the AI's identity and host application context.
 */
export interface AuraIdentityConfig {
  /** Metadata for the host application. */
  appMetadata: AppMetadata;
  /** Custom name for the AI assistant. */
  aiName?: string;
}

/**
 * UI configuration for the Aura chat component.
 */
export interface AuraAppearanceConfig {
  /** Title shown in the chat header. */
  headerTitle?: string;
  /** Icon shown in the chat header. */
  headerIcon?: string;
  /** Title for the initial welcome message. */
  welcomeMessageTitle?: string;
  /** Body of the initial welcome message. */
  welcomeMessage?: string | RichContent;
  /** List of prompt ideas to help the user get started. */
  suggestedPrompts?: SuggestedPrompt[];
  /** Placeholder text for the message input. */
  inputPlaceholder?: string;
  /** Custom message shown while the AI is thinking. */
  loadingMessage?: string;
  /** Custom message shown when an error occurrs. */
  errorMessage?: string;
  /** Label for the retry button. */
  retryLabel?: string;
  /** Whether to allow file uploads. */
  enableAttachments?: boolean;
  /** Max file size in bytes. */
  maxAttachmentSize?: number;
  /** Allowed MIME types for uploads. */
  allowedAttachmentTypes?: string[];
  /** Initial theme ("light", "dark", "auto"). */
  theme?: AuraTheme;
  /** Primary accent color. */
  primaryColor?: string;
  /** Custom font family. */
  fontFamily?: string;
}

/**
 * Root configuration object for the Aura AI Chat component.
 */
export interface AuraConfig {
  /** Identity and application context. */
  identity: AuraIdentityConfig;
  /** UI and theme configuration. */
  appearance?: AuraAppearanceConfig;
  /** Agent intelligence and tool configuration. */
  agent?: AuraAgentConfig;
  /** Callback for system events (tracking, logging, etc.). */
  onAuraEvent?: (event: AuraEvent) => void;
  /** Visibility and access control for the settings panel. */
  settingsModalConfig?: SettingsModalConfig;
}

/**
 * Interface for implementing custom storage for conversations and tool logs.
 */
export interface IConversationManager {
  /** Create a new conversation record. */
  createConversation?(conversation: Conversation): Promise<Conversation>;
  /** Get a single conversation by ID. */
  getConversation?(id: string): Promise<Conversation | undefined>;
  /** Load a full conversation into the chat. */
  loadConversation?(conversationId: string): Promise<Conversation | null>;
  /** List all available conversations for the user. */
  listConversations?(): Promise<Conversation[]>;
  /** Save a message to the persistent store. */
  saveMessage(
    conversationId: string,
    message: ChatMessage,
  ): Promise<void> | Promise<unknown>;
  /** Delete a conversation. */
  deleteConversation?(conversationId: string): Promise<void>;
  /** Clear all conversation history. */
  clearHistory?(): Promise<void>;
}
