import { css } from "lit";

export const lightTheme = css`
  :host([data-theme="light"]),
  :host(:not([data-theme])) {
    --aura-primary: #1a1a1a;
    --aura-accent: #187aba;
    --aura-accent-hover: #126a9e;
    --aura-warning: #f59e0b;
    --aura-error: #ef4444;
    --aura-success: #10b981;
    --aura-bg: #ffffff;
    --aura-border-color: #e5e7eb;
    --aura-muted-color: #6b7280;
    --aura-text-tertiary: #9ca3af;
    --aura-header-bg: #fafafa;
    --aura-input-bg: #ffffff;
    --aura-input-border: #d1d5db;
    --aura-msg-user-bg: #f3f4f6;
    --aura-msg-asst-bg: #eff6ff;
    --aura-msg-error-bg: #fef2f2;
    --aura-msg-error-fg: #991b1b;
    --aura-code-bg: #f8fafc;
    --aura-accent-light: #eff6ff;
    --aura-bg-surface: #ffffff;
    --aura-surface-subtle: #f8fafc;
    --aura-surface-hover: rgba(15, 23, 42, 0.045);
    --aura-surface-code: rgba(148, 163, 184, 0.14);
    --aura-overlay-bg: rgba(0, 0, 0, 0.4);
    --aura-scrollbar-thumb: #d1d5db;
    --aura-scrollbar-thumb-hover: #9ca3af;
    --aura-focus-ring: rgba(24, 122, 186, 0.12);
    --aura-debug: #94a3b8;
    --aura-json-string: #a31515;
    --aura-json-number: #098658;
    --aura-inverse-fg: #ffffff;
    --aura-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    --aura-shadow-strong: 0 8px 32px rgba(0, 0, 0, 0.18);

    --aura-fg: var(--aura-primary);
    --aura-header-fg: var(--aura-primary);
    --aura-msg-user-fg: var(--aura-primary);
    --aura-msg-asst-fg: var(--aura-primary);
    --aura-code-bg: #f8fafc;
    --aura-skill-card-bg: var(--aura-header-bg);
    --aura-skill-card-border: var(--aura-border-color);
    --aura-skill-card-color: var(--aura-text-primary);
    --aura-tool-badge-bg: var(--aura-accent-light);
    --aura-tool-badge-color: var(--aura-accent);
    --aura-color: var(--aura-fg);
    --aura-text-primary: var(--aura-fg);
    --aura-text-secondary: var(--aura-muted-color);
    --aura-text-color: var(--aura-text-secondary);
    --aura-text-error: var(--aura-error);
    --aura-title-color: var(--aura-fg);
    --aura-header-title-color: var(--aura-header-fg);
    --aura-header-icon-color: var(--aura-muted-color);
    --aura-action-color: var(--aura-muted-color);
    --aura-action-hover-bg: var(--aura-msg-user-bg);
    --aura-action-hover-color: var(--aura-primary);
    --aura-avatar-bg: var(--aura-msg-user-bg);
    --aura-avatar-color: var(--aura-muted-color);
    --aura-ai-avatar-bg: var(--aura-accent);
    --aura-user-message-bg: var(--aura-msg-user-bg);
    --aura-assistant-message-bg: var(--aura-msg-asst-bg);
    --aura-sender-color: var(--aura-muted-color);
    --aura-info: var(--aura-accent);
    --aura-ai: var(--aura-accent);
    --aura-skill: var(--aura-accent);
    --aura-json-key: var(--aura-accent);
    --aura-json-boolean: var(--aura-accent);
    --aura-json-null: var(--aura-muted-color);
    --aura-radius: 8px;
    --aura-font-sans: "Inter", "Segoe UI", system-ui, -apple-system, sans-serif;
    --aura-font-mono: "Cascadia Code", "Fira Code", "Consolas", monospace;
    --aura-font-family: var(--aura-font-sans);
  }
`;
